kind: pipeline
name: default


steps:
  - name: test
    image: golang
    commands:
      - go test -v -race `go list ./...`
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      registry: registry.strsqr.cloud
      repo: registry.strsqr.cloud/registry-webhook
      tags: latest